export const ROUTES = {
  FORBIDDEN: "/forbidden",
  LANDING: "/",
  HOME: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  ADMIN_PRODUCTS: "/admin/products",
  PUBLIC_PRODUCTS: "/products",
  ADMIN_INGREDIENTS: "/admin/ingredients",
  PUBLIC_INGREDIENTS: "/ingredients",
  ADMIN_CATEGORIES: "/admin/categories",
  PUBLIC_CATEGORIES: "/categories",
  ADMIN_USERS: "/admin/users",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  MY_ORDERS: "user/orders",
  ORDERS_ADMIN: "/orders",
  STOCK_INGREDIENTS: "/stock/ingredients",
} as const;
