export const ROUTES = {
  FORBIDDEN: "/forbidden",
  LANDING: "/",
  HOME: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PRODUCTS_DETAIL: "/admin/products/detail/:id",
  PUBLIC_PRODUCTS: "/products",
  ADMIN_INGREDIENTS: "/admin/ingredients",
  PUBLIC_INGREDIENTS: "/ingredients",
  ADMIN_CATEGORIES: "/admin/categories",
  PUBLIC_CATEGORIES: "/categories",
  ADMIN_USERS: "/admin/users",
} as const;
