export const ROUTES = {
  FORBIDDEN: "/forbidden",
  LANDING: "/",
  HOME: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  ADMIN_PRODUCTS: "/admin/products",
  STOCK_PRODUCTS_DETAIL: "/admin/products/detail/:id",
  PUBLIC_PRODUCTS: "/products",
  ADMIN_INGREDIENTS: "/admin/ingredients",
  PUBLIC_INGREDIENTS: "/ingredients",
  ADMIN_CATEGORIES: "/admin/categories",
  PUBLIC_CATEGORIES: "/categories",
  ADMIN_USERS: "/admin/users",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  CART: "/cart",
  MY_ORDERS: "/user/orders",
  ORDERS_ADMIN: "/orders",
  STOCK_INGREDIENTS: "/stock/ingredients",
  STOCK_PRODUCTS: "/stock/products",
  ADMIN_METRICS: "/admin/metrics",
  ADMIN_CONFIG: "/admin/config",
  KITCHEN_BOARD: "/kitchen",
} as const;
